export const HARD = [
 "", "   ", "...", "!!!", "42", "Hello.", "Run!", "Yes.", "No, thank you.",
 "THE CAT SAT ON THE MAT.",
 "I think, therefore I am.",
 "She said, \"I am coming home.\"",
 "The children (all six of them) ran outside.",
 "We hold these truths to be self-evident.",
 "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
 "The only thing we have to fear is fear itself.",
 "Ask not what your country can do for you; ask what you can do for your country.",
 "To be or not to be, that is the question.",
 "Happy families are all alike; every unhappy family is unhappy in its own way.",
 "The sun had set, and the stars were shining brightly in the dark sky.",
 "If you build it, he will come.",
 "My dog, who is very lazy, sleeps all day.",
 "The students who studied hard passed the exam easily.",
 "He ran quickly to the store, bought some milk, and came home.",
 "Although she was tired, she finished her homework before dinner.",
 "Whoever wins the race will receive a prize.",
 "The teacher made the students rewrite their essays.",
 "Can you tell me where the station is?",
 "Why did the chicken cross the road?",
 "Please sit down and be quiet.",
 "Don't touch that!",
 "Running is good exercise for the heart.",
 "The boy who cried wolf was not believed.",
 "Neither the teacher nor the students knew the answer.",
 "Both cats and dogs make good pets.",
 "I will go if it does not rain tomorrow.",
 "The book was written by a famous author in 1850.",
 "There is a house in New Orleans.",
 "A stitch in time saves nine.",
 "All that glitters is not gold.",
 "The quality of mercy is not strained.",
 "I wandered lonely as a cloud.",
 "The cat, the dog, and the mouse lived together peacefully.",
 "She is the girl whose bicycle was stolen.",
 "This is the house in which I was born.",
 "He is too tired to work.",
 "They watched the sun set over the mountains.",
 "Having finished his work, he went home.",
 "I saw a man with a telescope.",
 "Time flies like an arrow.",
 "Colorless green ideas sleep furiously.",
 "The horse raced past the barn fell.",
 "Buffalo buffalo buffalo.",
 "lol idk what this is supposed to be",
 "Supercalifragilisticexpialidocious!",
 "John's sister's friend's car broke down yesterday.",
 "He gave the dog a bone, and the dog wagged its tail happily.",
 "When I was young, I lived in a small village near the sea, where my father worked as a fisherman.",
]
