export const SPECIMENS = [
 "The old man walked slowly to the village.",
 "Birds sing.",
 "John and Mary don't like the very large dog that barked at them.",
 "She gave him a book about birds yesterday.",
 "They elected him president.",
 "Swimming in the lake is fun.",
 "I want to go home because I am tired.",
 "There are three apples on the table.",
 "Where did you put my keys?",
 "Oh, Mary, close the door!",
 "The letter written by her was lost.",
 "He picked up the phone and called his mother.",
 "I know that he is right.",
 "It's a beautiful day, isn't it?",
 "Four score and seven years ago our fathers brought forth on this continent a new nation.",
 "The quick brown fox jumps over the lazy dog.",
 "The man who lives next door is a doctor.",
 "When the sun rose, the birds began to sing.",
 "My brother, a doctor, works in Boston.",
 "The children laughed and played in the garden.",
 "She washed and dried the dishes.",
 "Apples, oranges, and pears are fruits.",
 "I came, I saw, I conquered.",
 "The house that Jack built is old.",
 "What he said was true.",
 "Who called?",
 "Is he happy?",
 "Did you see the movie?",
 "The tall and handsome stranger smiled.",
 "We painted the barn red.",
 "The boy sitting on the bench is my cousin.",
 "To err is human.",
 "He seems happy.",
 "The cat is on the mat.",
 "I enjoy reading books.",
 "She told me that she was leaving.",
 "Although it was raining, we went for a walk.",
 "The dog barked loudly, and the cat ran away.",
 "Let us go.",
 "The book I read was long.",
 "He is taller than his brother.",
 "Call me Ishmael.",
 "It was the best of times, it was the worst of times.",
 "All happy families are alike.",
 "The very old woman walked very slowly.",
 "I have been waiting for you.",
 "What a beautiful day it is!",
 "How old are you?",
 "The book on the table belongs to my sister.",
 "We the people of the United States, in order to form a more perfect union, establish this Constitution.",
 "In the beginning God created the heaven and the earth.",
 "Give me liberty or give me death!",
 "The man in the car waved at us.",
 "She made him a cake.",
 "Mary had a little lamb whose fleece was white as snow.",
 "Hello world",
 "the big red dog",
 "The sun gives light.",
 "Birds of beautiful plumage sing in the groves.",
 "The old man's daughter is very beautiful.",
 "Time and tide wait for no man.",
 "Honesty is the best policy.",
 "He that runs may read.",
 "Every pupil should study his lesson carefully.",
 "Slowly and silently the snow fell.",
 "The leaves of the trees were turning red and gold.",
 "We sat by the fire and told stories until midnight.",
 "The man whom you saw is my uncle.",
 "I do not know why he left.",
 "She sings beautifully, but she cannot dance.",
 "After the storm had passed, the children ran outside to play.",
 "Are you coming with us?",
 "Never give up.",
 "He was elected president of the society.",
 "The old man the boats.",
 "Swimming is fun.",
 "Reading books is fun.",
 "The only thing we have to fear is fear itself.",
 "To be or not to be, that is the question.",
 "All that glitters is not gold.",
 "Having finished his work, he went home.",
 "We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.",
 "And for the support of this Declaration, with a firm reliance on the protection of divine Providence, we mutually pledge to each other our Lives, our Fortunes and our sacred Honor.",
 "We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America.",
 "All legislative Powers herein granted shall be vested in a Congress of the United States, which shall consist of a Senate and House of Representatives.",
 "The executive Power shall be vested in a President of the United States of America.",
 "The judicial Power of the United States, shall be vested in one supreme Court, and in such inferior Courts as the Congress may from time to time ordain and establish.",
 "The enumeration in the Constitution, of certain rights, shall not be construed to deny or disparage others retained by the people.",
 "The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of sex.",
 "If men were angels, no government would be necessary.",
 "Ambition must be made to counteract ambition.",
 "Justice is the end of government.",
 "These are the times that try men's souls.",
 "Tyranny, like hell, is not easily conquered…",
 "We have it in our power to begin the world over again.",
 "Time makes more converts than reason.",
 "Society in every state is a blessing, but government even in its best state is but a necessary evil…",
 "Observe good faith and justice towards all nations; cultivate peace and harmony with all.",
 "The world will little note, nor long remember what we say here, but it can never forget what they did here.",
 "A house divided against itself cannot stand.",
 "You have seen how a man was made a slave; you shall see how a slave was made a man.",
 "Heaven is under our feet as well as over our heads.",
 "I went to the woods because I wished to live deliberately…",
 "The mass of men lead lives of quiet desperation.",
 "Trust thyself: every heart vibrates to that iron string.",
 "Nothing can bring you peace but yourself.",
 "To be great is to be misunderstood.",
 "A foolish consistency is the hobgoblin of little minds…",
 "I would prefer not to.",
 "I celebrate myself, and sing myself…",
 "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
 "Happy families are all alike; every unhappy family is unhappy in its own way.",
 "It was the best of times, it was the worst of times…",
 "All children, except one, grow up.",
 "Marley was dead: to begin with.",
 "There was no possibility of taking a walk that day.",
 "It was a dark and stormy night…",
 "In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since.",
 "Mrs. Dalloway said she would buy the flowers herself.",
 "In the late summer of that year we lived in a house in a village that looked across the river and the plain to the mountains.",
 "Through the fence, between the curling flower spaces, I could see them hitting.",
 "The Mole had been working very hard all the morning, spring-cleaning his little home.",
 "Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do…",
 "You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with such evil forebodings.",
 "Miss Brooke had that kind of beauty which seems to be thrown into relief by poor dress.",
 "The studio was filled with the rich odour of roses…",
 "Christmas won't be Christmas without any presents…",
 "Reader, I married him.",
 "I am no bird; and no net ensnares me…",
 "I would always rather be happy than dignified…",
 "Whatever our souls are made of, his and mine are the same…",
 "I declare, after all, there is no enjoyment like reading!",
 "I could easily forgive his pride, if he had not mortified mine.",
 "There is no charm equal to tenderness of heart…",
 "You pierce my soul.",
 "It is not down in any map; true places never are.",
 "It is a far, far better thing that I do, than I have ever done; it is a far, far better rest that I go to than I have ever known.",
 "I loved her against reason, against promise, against peace, against hope, against happiness, against all discouragement that could be.",
 "Why, sometimes I've believed as many as six impossible things before breakfast.",
 "We're all mad here.",
 "Beware, for I am fearless and therefore powerful.",
 "I'm not afraid of storms, for I'm learning how to sail my ship.",
 "What do we live for, if it is not to make life less difficult to each other?",
 "The only way to get rid of a temptation is to yield to it.",
 "Shall I compare thee to a summer's day?",
 "Thou art more lovely and more temperate…",
 "To be, or not to be, that is the question…",
 "The course of true love never did run smooth…",
 "We are such stuff as dreams are made on…",
 "All that glisters is not gold…",
 "The mind is its own place, and in itself can make a Heaven of Hell, a Hell of Heaven.",
 "No man is an island, entire of itself…",
 "Because I could not stop for Death, He kindly stopped for me…",
 "A thing of beauty is a joy for ever…",
 "We are all in the gutter, but some of us are looking at the stars.",
 "I can resist everything except temptation.",
 "I know that the man who called is here.",
 "I think the book that you lent me is lost.",
 "She said that the dog which barked was hers.",
 "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.",
 "Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.",
]
