export const SPECIMENS = [
 "The old man walked slowly to the village.",
 "Birds sing.",
 "John and Mary don't like the very large dog that barked at them.",
 "She gave him a book about birds yesterday.",
 "They elected him president.",
 "Swimming in the lake is fun.",
 "I want to go home because I am tired.",
 "There are three apples on the table.",
 "Where did you put my keys?",
 "Oh, Mary, close the door!",
 "The letter written by her was lost.",
 "He picked up the phone and called his mother.",
 "I know that he is right.",
 "It's a beautiful day, isn't it?",
 "Four score and seven years ago our fathers brought forth on this continent a new nation.",
 "The quick brown fox jumps over the lazy dog.",
 "The man who lives next door is a doctor.",
 "When the sun rose, the birds began to sing.",
 "My brother, a doctor, works in Boston.",
 "The children laughed and played in the garden.",
 "She washed and dried the dishes.",
 "Apples, oranges, and pears are fruits.",
 "I came, I saw, I conquered.",
 "The house that Jack built is old.",
 "What he said was true.",
 "Who called?",
 "Is he happy?",
 "Did you see the movie?",
 "The tall and handsome stranger smiled.",
 "We painted the barn red.",
 "The boy sitting on the bench is my cousin.",
 "To err is human.",
 "He seems happy.",
 "The cat is on the mat.",
 "I enjoy reading books.",
 "She told me that she was leaving.",
 "Although it was raining, we went for a walk.",
 "The dog barked loudly, and the cat ran away.",
 "Let us go.",
 "The book I read was long.",
 "He is taller than his brother.",
 "Call me Ishmael.",
 "It was the best of times, it was the worst of times.",
 "All happy families are alike.",
 "The very old woman walked very slowly.",
 "I have been waiting for you.",
 "What a beautiful day it is!",
 "How old are you?",
 "The book on the table belongs to my sister.",
 "We the people of the United States, in order to form a more perfect union, establish this Constitution.",
 "In the beginning God created the heaven and the earth.",
 "Give me liberty or give me death!",
 "The man in the car waved at us.",
 "She made him a cake.",
 "Mary had a little lamb whose fleece was white as snow.",
 "Hello world",
 "the big red dog",
]
